name: flutter_pcsc
description: Flutter plugin to access PCSC readers on Linux/Windows/MacOS
version: 0.0.3
repository: https://github.com/fabienrousseau/flutter_pcsc

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pcsc_linux: ^0.0.1
  flutter_pcsc_macos: ^0.0.1
  flutter_pcsc_platform_interface: ^0.0.1
  flutter_pcsc_windows: ^0.0.1
  ffi: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  plugin_platform_interface: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      linux:
        default_package: flutter_pcsc_linux
      macos:
        default_package: flutter_pcsc_macos
      windows:
        default_package: flutter_pcsc_windows
